name: CMake Tests

on: [push, workflow_dispatch]

env:
  CXX: clang++

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build

    - name: Build
      working-directory: ${{runner.workspace}}
      run: cmake --build build

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test_results_xml
        path: ${{runner.workspace}}/build/test-results/**/*.xml
